# Generated by Django 4.2.3 on 2023-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_controller_devicetype_sensor_controller_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Device: Types', 'verbose_name_plural': 'Device: Types'},
        ),
        migrations.AddField(
            model_name='controller',
            name='access_key',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
