# Generated by Django 4.2.3 on 2023-07-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_rename_ip_address_controller_network_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype'),
        ),
        migrations.AlterField(
            model_name='proximity',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.controller'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype'),
        ),
    ]
