# Generated by Django 4.2.3 on 2023-07-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_controller_type_alter_proximity_sensor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='unique_id',
            new_name='chip_id',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='unique_id',
            new_name='chip_id',
        ),
    ]
